-- Mod: potion
-- Code generated by the Simple Minetest Mod Maker
--   ( https://rubenwardy.github.io/minetest_mod_maker )

minetest.register_craft({
	output = "HealthPotion",
	type = "shapeless",
	recipe = {
		{"", "", ""},
		{"", "default:wood", ""},
		{"", "vessels:glass_bottle", ""},
	}
})